Snapshot

diff --git a/cadpod b/cadpod
--- a/cadpod
+++ b/cadpod
@@ -36,7 +36,7 @@ SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
 pod_start() {
     podman run \
         --name ${SITE_NAME} \
-        --rm --replace \
+        --rm --replace --detach \
         --env-file ${SCRIPT_DIR}/.env \
         --publish ${HOST_PORT}:${CONTAINER_PORT} \
         --volume ${SCRIPT_DIR}/data:${CONTAINER_DATADIR} \
@@ -54,28 +54,29 @@ service_generate() {
 }
 
 service_install() {
-    if [ ! -f "${SCRIPT_DIR}/${SYSTEMD_FILE}" ]; then
-        echo "Error: no unit file found. Run 'service generate' to create one."
-        exit 1
+    if [ -f "${SYSTEMD_PATH}/${SYSTEMD_FILE}" ]; then
+    	echo "Error: already installed in ${SYSTEMD_PATH}/${SYSTEMD_FILE}"
+	exit 1
+    else
+        if [ ! -f "${SCRIPT_DIR}/${SYSTEMD_FILE}" ]; then
+            echo "Error: no unit file found. Run 'service generate' to create one."
+            exit 1
+        else
+            mv "${SCRIPT_DIR}/${SYSTEMD_FILE}" "${SYSTEMD_PATH}/"
+            systemctl --user daemon-reload
+            systemctl --user start ${SITE_NAME}
+            systemctl --user enable ${SITE_NAME}
+            systemctl --user status ${SITE_NAME} | grep Active
+	fi
     fi
-    mv "${SCRIPT_DIR}/${SYSTEMD_FILE}" "${SYSTEMD_PATH}/"
-    systemctl --user daemon-reload
-    systemctl --user enable ${SITE_NAME}
-    systemctl --user start ${SITE_NAME}
-    systemctl --user status ${SITE_NAME}
 }
 
 service_remove() {
     systemctl --user disable ${SITE_NAME}
     systemctl --user stop ${SITE_NAME}
     if [ -f "${SYSTEMD_PATH}/${SYSTEMD_FILE}" ]; then
-       if [ ! -f "${SCRIPT_DIR}/${SYSTEMD_FILE}" ]; then
-            mv "${SYSTEMD_PATH}/${SYSTEMD_FILE}" "${SCRIPT_DIR}"
-            systemctl --user daemon-reload
-        else
-            echo "Error: conflicting file in ${SCRIPT_DIR}"
-            exit 1
-        fi
+        mv "${SYSTEMD_PATH}/${SYSTEMD_FILE}" "${SCRIPT_DIR}"
+        systemctl --user daemon-reload
     else
         echo "nothing to remove"
         ls "${SYSTEMD_PATH}"
@@ -86,17 +87,18 @@ site_generate() {
     local template="$CADDYFILE_TEMPLATE"
     eval "echo \"${template}\"" > "${SCRIPT_DIR}/${CADDY_FILE}"
     echo "writing to file ${SCRIPT_DIR}/${CADDY_FILE}:"
-    cat "${SCRIPT_DIR}/${CADDY_FILE}"
+    # cat "${SCRIPT_DIR}/${CADDY_FILE}"
 }
 
 site_enable() {
-    if [ ! -f "${CADDY_PATH}/${CADDY_FILE}" ]; then
-        if [ ! -f "${SCRIPT_DIR}/${CADDY_FILE}" ]; then
-            site_generate
-        fi
-        sudo mv "${SCRIPT_DIR}/${CADDY_FILE}" "${CADDY_DIR}/"
-        sudo systemctl reload caddy
+    if [ ! -f "${SCRIPT_DIR}/${CADDY_FILE}" ]; then
+        echo "generating Caddy file"
+        site_generate
     fi
+    sudo mv "${SCRIPT_DIR}/${CADDY_FILE}" "${CADDY_PATH}/${CADDY_FILE}"
+    sudo systemctl reload caddy
+    # cat "${CADDY_PATH}/${CADDY_FILE}"
+    sudo ls -l ${CADDY_PATH}
     echo "site enabled: https://${SITE_URLS}"
 }
 
@@ -105,10 +107,12 @@ site_disable() {
         if [ -f "${SCRIPT_DIR}/${CADDY_FILE}" ]; then
             echo "Error: conflicting file in ${SCRIPT_DIR}"
             exit 1
-        else
-            sudo mv "${CADDY_PATH}/${CADDY_FILE}" "${SCRIPT_DIR}/"
-            sudo systemctl reload caddy
-        fi
+	fi
+        sudo mv "${CADDY_PATH}/${CADDY_FILE}" "${SCRIPT_DIR}/"
+        sudo systemctl reload caddy
+    else
+        echo "Error: site not installed"
+	sudo ls ${CADDY_PATH}
     fi
     site_info
 }
@@ -118,19 +122,50 @@ site_info() {
     curl ${SITE_URLS}
 }
 
+auto_install() {
+    echo "starting pod"
+    pod_start
+    echo "generating service file"
+    service_generate
+    echo "stopping pod"
+    podman rm -f "${SITE_NAME}"
+    echo "installing service"
+    service_install
+    echo "generating site file"
+    site_generate
+    echo "enabling site"
+    site_enable
+    echo "checking service status"
+    cat ${SYSTEMD_PATH}/${SYSTEMD_FILE}
+    systemctl --user status ${SITE_NAME}
+    echo "checking site status"
+    curl https://${SITE_URLS}
+}
+
+auto_remove() {
+    site_disable
+    service_remove
+}
+
 case "$1" in
 pod)
     if   [ "$2" = "start" ];    then pod_start
     elif [ "$2" = "stop" ];     then podman kill ${SITE_NAME}
     elif [ "$2" = "log" ];      then podman logs -f ${SITE_NAME}
-    else podman ps
+    else
+        echo "Error: sub-command unknown"
+	exit 1
     fi
     ;;
 site)
     if   [ "$2" = "enable" ];   then site_enable
+    elif [ "$2" = "install" ];  then site_enable
     elif [ "$2" = "disable" ];  then site_disable
+    elif [ "$2" = "remove" ];   then site_disable
     elif [ "$2" = "generate" ]; then site_generate
-    else site_info
+    else
+        echo "Error: sub-command unknown"
+	exit 1
     fi
     ;;
 service)
@@ -142,8 +177,16 @@ service)
     elif [ "$2" = "start" ];    then systemctl --user start ${SITE_NAME}
     elif [ "$2" = "stop" ];     then systemctl --user stop ${SITE_NAME}
     elif [ "$2" = "status" ];   then systemctl --user status ${SITE_NAME}
-    else systemctl --user list-units --type=service | grep Podman
+    else
+        echo "Error: sub-command unknown"
+	exit 1
     fi
+    ;;
+install)
+    auto_install
+    ;;
+remove)
+    auto_remove
     ;;
 *)
     echo "Error: command not found" >&2
